version: 0.2

phases:
  build:
    commands:
      - touch source1_file
      - echo "AWS_DEFAULT_REGION $AWS_DEFAULT_REGION" >> source1_file
      - echo "AWS_REGION $AWS_REGION" >> source1_file
      - echo "CODEBUILD_BUILD_ARN $CODEBUILD_BUILD_ARN" >> source1_file
      - echo "CODEBUILD_BUILD_ID $CODEBUILD_BUILD_ID" >> source1_file
      - echo "CODEBUILD_BUILD_IMAGE $CODEBUILD_BUILD_IMAGE" >> source1_file
      - echo "CODEBUILD_BUILD_NUMBER $CODEBUILD_BUILD_NUMBER" >> source1_file
      - echo "CODEBUILD_BUILD_SUCCEEDING $CODEBUILD_BUILD_SUCCEEDING" >> source1_file
      - echo "CODEBUILD_INITIATOR $CODEBUILD_INITIATOR" >> source1_file
      - echo "CODEBUILD_KMS_KEY_ID $CODEBUILD_KMS_KEY_ID" >> source1_file
      - echo "CODEBUILD_LOG_PATH $CODEBUILD_LOG_PATH" >> source1_file
      - echo "CODEBUILD_RESOLVED_SOURCE_VERSION $CODEBUILD_RESOLVED_SOURCE_VERSION" >> source1_file
      - echo "CODEBUILD_SOURCE_REPO_URL $CODEBUILD_SOURCE_REPO_URL" >> source1_file
      - echo "CODEBUILD_SOURCE_VERSION $CODEBUILD_SOURCE_VERSION" >> source1_file
      

artifacts:
  files:
    - source1_file
  base-directory: $CODEBUILD_SRC_DIR
