version: 0.2

phases:
  install:
    commands:
      - echo Install Step

  pre_build:
    commands:
      - echo Pre-build Step
      - curl http://deeplearning.net/data/mnist/mnist.pkl.gz -o mnist.pkl.gz

  build:
    commands:
      - echo Build Step
      - ls *.py


artifacts:
  files:
    - mnist.pkl.gz
    - preprocess.py
    - train.py

  base-directory: $CODEBUILD_SRC_DIR
